### ISSUE TITLE
Lua Error 

### ISSUE THREAD

**Issue by gaveer** [WowRarity/Rarity#473] opened 2022-04-10 19:09 UTC
```
1x ...nterface\Rarity\Core\GUI\GameTooltipHooks.lua:29: attempt to index field 'db' (a nil value)
[string "@Rarity\Core\GUI\GameTooltipHooks.lua"]:29: in function <...nterface\Rarity\Core\GUI\GameTooltipHooks.lua:27>
[string "=[C]:"]: ?
[string "=[C]:"]: ?
[string "=[C]:"]: ?
[string "=[C]:"]: ?
[string "=[C]:"]: ?
```

**Comment by Duckwhale** [comment] 2022-04-13 21:26
When does this occur? Is it reproducible? It seems like something that could be caused by another addon; have you tried disabling all others to see if it still happens?

**Comment by gaveer** [comment] 2022-04-13 22:23
when i `/reload`

**Comment by gaveer** [comment] 2022-04-13 22:31
```
-- Game Tooltip hijacking stuff
_G.GameTooltip:HookScript("OnTooltipSetUnit", function(self)
	-- If debug mode is on, find NPCID from mouseover target and append it to the tooltip
	if R.db.profile.debugMode then
		GameTooltip:AddLine("NPCID: " .. R:GetNPCIDFromGUID(UnitGUID("mouseover")), 255, 255, 255)
	end

	if not R.db or R.db.profile.enableTooltipAdditions == false then
		return
	end
	```

**Comment by Duckwhale** [comment] 2022-11-17 07:21
Duplicate of #508 (presumably).

**Closed by Duckwhale** 2022-11-17 07:21 UTC
Labels: Status: Duplicate
