### ISSUE TITLE
Rustfeather not counting kill if you farm the mount with a char that didn't do mechagon intro.

### ISSUE THREAD

**Issue by formigao** [WowRarity/Rarity#463] opened 2022-02-14 20:55 UTC
I'm farming this with many char and the ones that didnt do intro quests dont count the kill.

**Comment by Duckwhale** [comment] 2022-02-15 18:32
I can't reproduce this issue, and Rarity also doesn't detect whether you have completed the intro quests. Whenever you loot the NPC, it adds an attempt. That's really all there is to it.

You could check your alt's settings, make sure the item is enabled and they aren't using a different profile. If there's no difference and you still can't get any attempts, I'll need more information (such as a debug log/error message hinting at a problem) :)

**Comment by formigao** [comment] 2022-02-15 18:51
im going to kill him and record it for you

**Comment by Duckwhale** [comment] 2022-08-03 10:06
Seems like this could not be reproduced? I'll close it for now; feel free to comment if the issue persists.

**Closed by Duckwhale** 2022-08-03 10:06 UTC
Labels: Status: Needs Confirmation, Type: Bug
