### ISSUE TITLE
Update 9.1.5 causing error. 1110: Attempt to register unknown event "ITEM_UPGRADE_MASTER_UPDATE"

### ISSUE THREAD

**Issue by Ookami313** [WowRarity/Rarity#429] opened 2021-11-02 23:38 UTC
I'm receiving the following error upon logging into the game after updating to 9.1.5, Thanks.

1x Broker_Everything\shared.lua:1110: Attempt to register unknown event "ITEM_UPGRADE_MASTER_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Broker_Everything\shared.lua"]:1110: in function <Broker_Everything\shared.lua:1100>
[string "@Broker_Everything\shared.lua"]:1130: in function `Init'
[string "@Broker_Everything\modules/gps.lua"]:523: in function <Broker_Everything\modules/gps.lua:470>
[string "@Broker_Everything\modules/gps.lua"]:606: in function `init'
[string "@Broker_Everything\modules.lua"]:58: in function <Broker_Everything\modules.lua:48>
[string "@Broker_Everything\modules.lua"]:190: in function `moduleInit'
[string "@Broker_Everything\core.lua"]:76: in function <Broker_Everything\core.lua:36>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "ITEM_UPGRADE_MASTER_UPDATE"

**Comment by Dawawe** [comment] 2021-11-03 01:48
Im getting

**Comment by Duckwhale** [comment] 2021-11-03 02:37
From the patch notes:

> Item Upgrade UI has been reworked.

However, Rarity does not listen to this event. What makes you think this error is caused by Rarity, @Ookami313? It appears to be an unrelated problem, so I'm not really sure what I could do to fix it.

Since the patch isn't yet live on EU servers I can't check for myself, but I see no way the unrelated Item Upgrade UI changes could possibly affect Rarity's functionality.

@Dawawe This is a separate issue; please check #430 for status updates as I research the problem (after the patch goes live here) :)

**Comment by Ookami313** [comment] 2021-11-03 03:30
Yea, sorry about that. I seem to have grabbed the wrong error when I posted. So many errors popped I grabbed one for a different addon. When i get a second I'll reload and get a fresh list of errors to find the one for Rarity. Thanks.

**Comment by Ookami313** [comment] 2021-11-03 03:48
Found the error. It's the same LibQTip: 48 that was posted as #430. So feel free to close this ticket. Thanks.

**Comment by Duckwhale** [comment] 2021-11-03 16:07
Gotcha, closing this as invalid then :)

**Closed by Duckwhale** 2021-11-03 16:07 UTC
