### ISSUE TITLE
Random LUA error

### ISSUE THREAD

**Issue by Andf** [WowRarity/Rarity#745] opened 2024-08-20 16:10 UTC
Hello,

I'm getting this random LUA error but I can't link to a specific event:

++++
50x Rarity/Core/GUI/GameTooltipHooks.lua:524: Failed to extract item ID from item link (format might have changed?)
[string "=[C]"]: in function `assert'
[string "@Rarity/Core/GUI/GameTooltipHooks.lua"]:524: in function <Rarity/Core/GUI/GameTooltipHooks.lua:513>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1553: in function `OnUpdate'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1512: in function `OnEnter'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1508: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1507>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "Failed to extract item ID from item link (format might have changed?)"

**Comment by Duckwhale** [comment] 2024-08-20 16:20
Thanks for the report. This is a duplicate of #740 and should be fixed once #744 has landed (i.e., in the next release, coming soon).

**Closed by Duckwhale** 2024-08-20 16:20 UTC

**Comment by Andf** [comment] 2024-08-21 15:00
Thanks!
