### ISSUE TITLE
Holiday reminders aren't displayed after logging in, until the main window is opened (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#492] opened 2022-10-26 22:58 UTC
Source: [Discord](https://discord.com/channels/788119147740790854/788119314909626388/1034115793572614154)
> Mine holiday reminder only shows me when i mouse over the mini rarity icon, then the text shows up in the middle of the screen, it dosent show when i log in on new character only when i mouse over it. How do i fix it?

**Comment by godejord** [comment] 2022-10-27 11:02
Duplicate of #312

**Closed** 2022-10-27 21:23 UTC
Labels: Priority: Low, Status: Duplicate, Type: Bug, Complexity: TBD, Category: GUI
