### ISSUE TITLE
Rukhmar kill count increases for invalid additional kills in same week

### ISSUE THREAD

**Issue by GeoffreyEmerson** [WowRarity/Rarity#458] opened 2022-02-06 21:07 UTC
I don't know if this issue affects other weekly/daily rares, but if you kill Rukhmar twice in a row, the "attempts" counter increases even though there was no possible drop after the first kill per week per toon.

**Comment by Duckwhale** [comment] 2022-02-08 03:03
Hello! This appears to be a duplicate of https://github.com/WowRarity/Rarity/issues/161.

Essentially, Rarity relies on Blizzard's kill statistics to determine attempts for world bosses. This is generally the most reliable avenue we have available, though it does assume people won't go and kill bosses after they've received their weekly loot. If they do, Blizzard's statistics will be updated and with them, our attempts count.

Since this isn't something we can easily fix, I'm afraid that's just something we have to live with... :(

PS: Closing this as a duplicate. In no way do I want to discourage discussions!

**Closed by Duckwhale** 2022-02-08 03:03 UTC
